"""Training entry point for SparseChron."""

import os
os.environ["PYTORCH_ALLOC_CONF"] = "expandable_segments:True"
os.environ.setdefault("PYTORCH_CUDA_ALLOC_CONF", "expandable_segments:True")  # torch < 2.3 reads the old variable

import json
import random
from pathlib import Path

import numpy as np
import tyro
import torch

from sparsechron.utils.config import TrainConfig
from sparsechron.models.gaussians import GaussianModel
from sparsechron.models.renderer import GaussianRenderer
from sparsechron.data.dataset import SceneDataset
from sparsechron.training.scheduler import DensificationScheduler
from sparsechron.training.trainer import Trainer
from sparsechron.preprocessing.init_gaussians import initialize_gaussians


def read_ply(ply_path: Path, device: torch.device):
    """Simple parser for ASCII PLY files generated by pose estimation."""
    with open(ply_path, "r", encoding="utf-8") as f:
        lines = f.readlines()

    data_start = 0
    vertex_count = 0
    for i, line in enumerate(lines):
        line = line.strip()
        if line.startswith("element vertex"):
            vertex_count = int(line.split()[-1])
        if line == "end_header":
            data_start = i + 1
            break

    points = []
    colors = []
    for line in lines[data_start:data_start+vertex_count]:
        parts = line.split()
        if len(parts) >= 6:
            points.append([float(parts[0]), float(parts[1]), float(parts[2])])
            colors.append([float(parts[3])/255.0, float(parts[4])/255.0, float(parts[5])/255.0])

    if not points:
        raise ValueError(f"No vertices parsed from {ply_path}. Is it a valid ASCII PLY?")

    points_tensor = torch.tensor(points, dtype=torch.float32, device=device)
    colors_tensor = torch.tensor(colors, dtype=torch.float32, device=device)
    return points_tensor, colors_tensor


def set_seed(seed: int) -> None:
    """Seeds all RNGs used by the training loop for reproducibility."""
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def compute_scene_transform(points: torch.Tensor):
    """Computes a (center, scale) transform mapping the init cloud into a unit box.

    The 98th-percentile radius is used instead of the max so outlier points
    (common in DUSt3R/points.npy clouds) cannot blow up the scale.

    Returns:
        (center, scale) with center as a (3,) float tensor and scale as float.
    """
    center = points.mean(dim=0)
    dists = (points - center).norm(dim=-1)
    scale = float(torch.quantile(dists, 0.98).clamp_min(1e-6).item())
    return center, scale


def main() -> None:
    """Parses config from CLI and runs training."""
    config = tyro.cli(TrainConfig)

    if not torch.cuda.is_available():
        raise SystemExit(
            "CUDA is required: SparseChron uses the gsplat CUDA rasterizer. "
            "On Kaggle, enable Settings -> Accelerator -> GPU before running."
        )
    device = torch.device("cuda")

    set_seed(config.seed)

    dataset = SceneDataset(config.scene_dir)
    if config.debug_single_batch:
        print("DEBUG SINGLE BATCH MODE: Restricting dataset to 1 image.")
        dataset.image_paths = dataset.image_paths[:1]
        dataset.cameras = dataset.cameras[:1]

    ply_path = Path(config.scene_dir) / "init_gaussians.ply"
    if ply_path.exists():
        print(f"Loading initial points from {ply_path}")
        points, colors = read_ply(ply_path, device)
    else:
        print(f"Warning: {ply_path} not found. Falling back to random initialization.")
        num_points = 10_000
        points = (torch.rand(num_points, 3, device=device) - 0.5) * 2.0
        colors = torch.rand(num_points, 3, device=device)

    # Scene normalization keeps scale-dependent thresholds (split/prune/noise,
    # deformation frequency encoding) meaningful across datasets.
    scene_transform = None
    if config.normalize_scene:
        center, scale = compute_scene_transform(points)
        points = (points - center) / scale
        scene_transform = (center.cpu().numpy(), scale)
        dataset.apply_scene_transform(scene_transform)
        print(f"Scene normalized: center={scene_transform[0].tolist()}, scale={scale:.4f}")

    init_dict = initialize_gaussians(points, colors)
    model = GaussianModel(init_dict).to(device)

    optimizer = torch.optim.Adam(
        [
            {"params": [model._positions], "lr": config.lr_position, "name": "positions"},
            {"params": [model._scales], "lr": config.lr_scale, "name": "scales"},
            {"params": [model._rotations], "lr": config.lr_rotation, "name": "rotations"},
            {"params": [model._opacities], "lr": config.lr_opacity, "name": "opacities"},
            {"params": [model._sh_coeffs], "lr": config.lr_sh, "name": "sh_coeffs"},
        ],
        lr=0.0,
        eps=1e-15,
    )

    renderer = GaussianRenderer()

    scheduler = DensificationScheduler(
        model=model,
        optimizer=optimizer,
        max_gaussians=config.max_gaussians,
        densify_interval=config.densify_interval,
        prune_interval=config.prune_interval,
        grad_threshold=config.densify_grad_threshold,
        min_opacity=config.prune_min_opacity,
        max_scale=config.prune_max_scale,
        split_scale_threshold=config.split_scale_threshold,
        clone_noise=config.clone_noise,
    )

    # Persist the normalization so evaluation can apply the identical transform.
    output_dir = Path(config.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    if scene_transform is not None:
        with open(output_dir / "scene_transform.json", "w") as f:
            json.dump(
                {"center": scene_transform[0].tolist(), "scale": scene_transform[1]},
                f,
                indent=2,
            )

    # Held-out split for periodic validation renders + PSNR.
    val_dataset = None
    try:
        val_dataset = SceneDataset(
            config.scene_dir, split="test", scene_transform=scene_transform
        )
        print(f"Validation split: {len(val_dataset)} held-out images.")
    except Exception as e:  # noqa: BLE001 - validation is optional
        print(f"Warning: validation dataset unavailable ({e}); skipping periodic eval.")

    trainer = Trainer(
        config=config,
        model=model,
        optimizer=optimizer,
        dataset=dataset,
        renderer=renderer,
        scheduler=scheduler,
        val_dataset=val_dataset,
    )

    trainer.train()

if __name__ == "__main__":
    main()
