"""Training entry point for SparseChron."""

import tyro
import torch

from sparsechron.utils.config import TrainConfig
from sparsechron.models.gaussians import GaussianModel
from sparsechron.models.renderer import GaussianRenderer
from sparsechron.data.dataset import SceneDataset
from sparsechron.training.scheduler import DensificationScheduler
from sparsechron.training.trainer import Trainer
from sparsechron.preprocessing.init_gaussians import initialize_gaussians
from sparsechron.preprocessing.init_gaussians import initialize_gaussians
from pathlib import Path


def read_ply(ply_path: Path, device: torch.device):
    """Simple parser for ASCII PLY files generated by pose estimation."""
    with open(ply_path, "r", encoding="utf-8") as f:
        lines = f.readlines()
        
    data_start = 0
    vertex_count = 0
    for i, line in enumerate(lines):
        line = line.strip()
        if line.startswith("element vertex"):
            vertex_count = int(line.split()[-1])
        if line == "end_header":
            data_start = i + 1
            break
            
    points = []
    colors = []
    for line in lines[data_start:data_start+vertex_count]:
        parts = line.split()
        if len(parts) >= 6:
            points.append([float(parts[0]), float(parts[1]), float(parts[2])])
            colors.append([float(parts[3])/255.0, float(parts[4])/255.0, float(parts[5])/255.0])
            
    points_tensor = torch.tensor(points, dtype=torch.float32, device=device)
    colors_tensor = torch.tensor(colors, dtype=torch.float32, device=device)
    return points_tensor, colors_tensor
def main() -> None:
    """Parses config from CLI and runs training."""
    config = tyro.cli(TrainConfig)
    
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    
    dataset = SceneDataset(config.scene_dir)
    if config.debug_single_batch:
        print("DEBUG SINGLE BATCH MODE: Restricting dataset to 1 image.")
        dataset.image_paths = dataset.image_paths[:1]
        dataset.cameras = dataset.cameras[:1]
        
    ply_path = Path(config.scene_dir) / "init_gaussians.ply"
    if ply_path.exists():
        print(f"Loading initial points from {ply_path}")
        points, colors = read_ply(ply_path, device)
    else:
        print(f"Warning: {ply_path} not found. Falling back to random initialization.")
        num_points = 10_000
        points = (torch.rand(num_points, 3, device=device) - 0.5) * 5.0
        colors = torch.rand(num_points, 3, device=device)
    
    init_dict = initialize_gaussians(points, colors)
    model = GaussianModel(init_dict).to(device)
    
    optimizer = torch.optim.Adam(
        [
            {"params": [model._positions], "lr": config.lr_position, "name": "positions"},
            {"params": [model._scales], "lr": config.lr_scale, "name": "scales"},
            {"params": [model._rotations], "lr": config.lr_rotation, "name": "rotations"},
            {"params": [model._opacities], "lr": config.lr_opacity, "name": "opacities"},
            {"params": [model._sh_coeffs], "lr": config.lr_sh, "name": "sh_coeffs"},
        ],
        lr=0.0,
        eps=1e-15,
    )
    
    renderer = GaussianRenderer()
    
    scheduler = DensificationScheduler(
        model=model,
        optimizer=optimizer,
        max_gaussians=config.max_gaussians,
        densify_interval=config.densify_interval,
        prune_interval=config.prune_interval,
    )
    
    trainer = Trainer(
        config=config,
        model=model,
        optimizer=optimizer,
        dataset=dataset,
        renderer=renderer,
        scheduler=scheduler,
    )
    
    trainer.train()

if __name__ == "__main__":
    main()
